[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[env]
# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL = "https://qfregiogzspihbglvpqs.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcmVnaW9nenNwaWhiZ2x2cHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Njc4NTUsImV4cCI6MjA3MjI0Mzg1NX0.DeEm08k7QOrKObWaz8AUaOB5N6Z2QZhZHFaUf2siALA"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcmVnaW9nenNwaWhiZ2x2cHFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjY2Nzg1NSwiZXhwIjoyMDcyMjQzODU1fQ.4iyWL8ArcNEshVoGPZfaMXeHlawAqEjrMjA2Xp6puRM"

# Environment
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
NEXT_PUBLIC_API_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}/api"
NEXT_PUBLIC_BASE_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"

# WhatsApp & Payment Configuration  
NEXT_PUBLIC_WHATSAPP_NUMBER = "+5491166599559"
NEXT_PUBLIC_PAYMENT_EMAIL = "ecucondor@gmail.com"

# Company Information
NEXT_PUBLIC_COMPANY_NAME = "Ecucondor SAS"
NEXT_PUBLIC_COMPANY_RUC = "1391937000OO-1"
NEXT_PUBLIC_COMPANY_BANK = "Produbanco"
NEXT_PUBLIC_COMPANY_BANK_ACCOUNT_TYPE = "Cuenta Corriente"
NEXT_PUBLIC_COMPANY_DOMAIN = "ecucondor.com"